const KEY='akari-webmcp-mv-project-v1';let project=JSON.parse(localStorage.getItem(KEY)||'null');
const $=id=>document.getElementById(id);const save=()=>{localStorage.setItem(KEY,JSON.stringify(project));render()};
function plan(){if(!project)return null;const mood=$("mood").value;project.title=$("title").value||'Doodle MV';project.mood=mood;project.shots=[0,5,10].map((start,i)=>({id:`shot-${i+1}`,start,end:start+5,action:[`The doodle wakes in a ${mood} room`,`Camera follows its changing silhouette`,`A soft return to the first line`][i],prompt:`15s MV, ${mood} mood, hand-drawn doodle, shot ${i+1}, gentle camera motion` }));project.updatedAt=new Date().toISOString();save();$("status").textContent='Plan ready. Human and agent now share this project.'}
function render(){ $("projectTitle").textContent=project?project.title:'No project yet';$("analysis").textContent=project?`Doodle: ${project.fileName} · mood: ${project.mood} · updated ${project.updatedAt}`:'Upload a doodle to begin.';$("shots").innerHTML=project?project.shots.map(s=>`<article class="shot"><b>${s.id} · ${s.start}–${s.end}s</b><br>${s.action}<br><small>${s.prompt}</small></article>`).join(''):'' }
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;project={id:crypto.randomUUID(),fileName:f.name,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),mood:'dream',shots:[]};$("fileLabel").textContent=f.name;$("analysis").textContent='Local analysis: hand-drawn image ready for a shared plan.';save()};$("create").onclick=plan;$("save").onclick=()=>{if(project){save();$("status").textContent='Saved to local project history.'}};$("prepare").onclick=()=>{if(!project)return;$("status").textContent='prompt_ready · no provider credential/executor verified · no fake video claimed'};
function register(){const mc=navigator.modelContext;if(!mc)return;const schema=(properties,required=[])=>({type:'object',properties,required,additionalProperties:false});const current=()=>project;const write=p=>{project=p;save();return{ok:true,project:p}};const tools=[
{name:'read_current_mv_project',title:'Read current MV project',description:'Read the project humans see in this atelier.',inputSchema:schema({}),execute:()=>current()?{ok:true,project:current()}:{ok:false,reason:'no_mv_project'}},
{name:'analyze_current_doodle',title:'Analyze current doodle',description:'Return the local doodle analysis.',inputSchema:schema({}),execute:()=>current()?{ok:true,fileName:current().fileName,analysis:'hand-drawn image ready'}:{ok:false,reason:'no_mv_project'}},
{name:'create_mv_plan',title:'Create MV plan',description:'Create the shared three-shot plan.',inputSchema:schema({mood:{type:'string'},title:{type:'string'}}),execute:i=>{if(!current())return{ok:false,reason:'no_mv_project'};project.title=i.title||project.title;project.mood=i.mood||project.mood;plan();return{ok:true,project}}},
{name:'set_mood',title:'Set mood',description:'Regenerate the shared plan with a mood.',inputSchema:schema({mood:{type:'string'}},['mood']),execute:i=>{if(!current())return{ok:false,reason:'no_mv_project'};project.mood=i.mood;plan();return{ok:true,project}}},
{name:'propose_shot',title:'Propose a shot',description:'Read one shot for human review.',inputSchema:schema({shotId:{type:'string'}}),execute:i=>{const s=current()?.shots.find(x=>x.id===i.shotId);return s?{ok:true,shot:s}:{ok:false,reason:'shot_not_found'}}},
{name:'rewrite_shot',title:'Rewrite a shot',description:'Update one shot visible to the human.',inputSchema:schema({shotId:{type:'string'},action:{type:'string'},prompt:{type:'string'}},['shotId']),execute:i=>{if(!current())return{ok:false,reason:'no_mv_project'};const s=project.shots.find(x=>x.id===i.shotId);if(!s)return{ok:false,reason:'shot_not_found'};if(i.action)s.action=i.action;if(i.prompt)s.prompt=i.prompt;project.updatedAt=new Date().toISOString();return write(project)}},
{name:'reorder_shots',title:'Reorder shots',description:'Reorder all shots without dropping any.',inputSchema:schema({orderedIds:{type:'array',items:{type:'string'}}},['orderedIds']),execute:i=>{if(!current()||i.orderedIds.length!==project.shots.length||new Set(i.orderedIds).size!==i.orderedIds.length)return{ok:false,reason:'ordered_ids_must_match_all_shots'};const m=new Map(project.shots.map(s=>[s.id,s]));project.shots=i.orderedIds.map(id=>m.get(id)).filter(Boolean);return write(project)}},
{name:'inspect_provider_availability',title:'Inspect provider availability',description:'Return truthful local provider status.',inputSchema:schema({}),execute:()=>({ok:true,providers:[{provider:'prompt-only',enabled:true,mode:'prompt-only',reason:'safe deterministic fallback'},{provider:'external',enabled:false,mode:'prompt-only',reason:'credential/executor not verified'}]})},
{name:'save_mv_project',title:'Save MV project',description:'Persist the shared project.',inputSchema:schema({}),execute:()=>current()?(save(),{ok:true,projectId:project.id,storage:'localStorage'}):{ok:false,reason:'no_mv_project'}},
{name:'render_or_prepare_video',title:'Render or prepare video',description:'Prepare without claiming fake completion.',inputSchema:schema({}),execute:()=>current()?{ok:true,status:'prompt_ready',projectId:project.id,reason:'No live provider credential/executor verified; prompt-only fallback'}:{ok:false,reason:'no_mv_project'}}];tools.forEach(t=>mc.registerTool(t));}
render();register();
